name: Periodic health check

on:
  push:
    branches: [main]   # for testing first
  schedule:
    - cron: '0 0 * * *'   # once per day (safe for free tier)

jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Ping deployed application
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-edfe.onrender.com/health
          max-attempts: 3
          retry-delay: 5s
