name: Deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    outputs:
      can_deploy: ${{ steps.deploy.outcome == 'success' }}
      skip: ${{ steps.skip.outputs.skip }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run end-to-end tests
        run: npm run test:e2e

      - name: Check skip flag
        id: skip
        if: ${{ github.event_name == 'push' }}
        run: |
          COMMITS=$(jq -r '.commits[].message' "$GITHUB_EVENT_PATH" || true)

          if echo "$COMMITS" | grep -q '#skip'; then
          echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Trigger deployment
        id: deploy
        if: ${{ github.event_name == 'push' && steps.skip.outputs.skip == 'false' }}
        run: |
          curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      
      - name: Notify Discord on failure
        uses: rjstone/discord-webhook-notify@v2
        if: failure()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          title: Build failed âŒ
          details: |
            Commit: ${{ github.sha }}
            Message: ${{ github.event.head_commit.message }}

      - name: Notify Discord on successful deployment
        uses: rjstone/discord-webhook-notify@v2
        if: success() && steps.deploy.outcome == 'success'
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          title: Deployment successful ðŸš€
          details: |
            Commit: ${{ github.sha }}
            Message: ${{ github.event.head_commit.message }}

  tag_release:
    needs: simple_deployment_pipeline
    runs-on: ubuntu-latest

    if: >
      ${{
        github.event_name == 'push' &&
        needs.simple_deployment_pipeline.outputs.skip == 'false' &&
        needs.simple_deployment_pipeline.outputs.can_deploy == 'true'}}

    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
